name: utrecht-personals
services:
- name: web
  github:
    repo: your-username/utrecht-personals
    branch: master
  source_dir: /
  dockerfile_path: Dockerfile
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
  routes:
  - path: /
