name: utrecht-personals
services:
- name: web
  github:
    repo: your-username/utrecht-personals
    branch: main
  source_dir: /
  dockerfile_path: dockerfile
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
domains:
- domain: utrecht-personals.com
  type: PRIMARY
  zone: utrecht-personals.com
