name: utrecht-personals
services:
- name: web
  github:
    repo: your-username/utrecht-personals
    branch: master
  source_dir: /
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
  routes:
  - path: /
